export const DEFAULT_WORD_LIST: string[] = [
  "angel",
  "anvil",
  "balloon",
  "batman",
  "beard",
  "bell",
  "bikini",
  "bird",
  "bodice",
  "bowtie",
  "bust",
  "🍑",
  "butterfly",
  "cathedral",
  "coconuts",
  "coffin",
  "controller",
  "creeper",
  "crown",
  "disappointed",
  "dreidel",
  "dress",
  "drone",
  "egg",
  "eyes",
  "feet",
  "fish",
  "footprint",
  "footprint",
  "gem",
  "goomba",
  "hat",
  "heart",
  "helicopter",
  "helmet",
  "hipbone",
  "key",
  "leaf",
  "LSP",
  "lungs",
  "maraca",
  "moustache",
  "mouth",
  "muffin",
  "mushroom",
  "nose",
  "onion",
  "pacman",
  "pants",
  "peanut",
  "🍆",
  "pokemon",
  "poop",
  "smile",
  "sombrero",
  "squid",
  "stingray",
  "tie",
  "tongue",
  "UFO",
  "🌮",
  "vest",
  "voldemort",
];

export const DEFAULT_DISABLED_WORDS: ReadonlySet<string> = new Set([]);

// export const DEFAULT_WORD_LIST: string[] = [
//   "angel",
//   "anger",
//   "batman",
//   "beard",
//   "butterfly",
//   "clothing",
//   "clown",
//   "dreidel",
//   "dress",
//   "egg",
//   "evil",
//   "eyes",
//   "feet",
//   "fish",
//   "formalwear",
//   "helicopter",
//   "hipbone",
//   "jelly",
//   "leaf",
//   "lungs",
//   "maraca",
//   "moustache",
//   "mouth",
//   "🍄",
//   "onion",
//   "orbital",
//   "pacman",
//   "pants",
//   "peanut",
//   "🍆",
//   "poop",
//   "snake",
//   "squid",
//   "tongue",
//   "🌮",
//   "voldemort",
//   "walnut",
//   "water",
// ];

// export const DEFAULT_DISABLED_WORDS: ReadonlySet<string> = new Set([
//   // "ball",
//   // "snake",
//   // "leaf",
//   // "mouth",
//   // "dress",
//   // "mushroom",
//   // "orbital",
//   // "peanut",
//   // "tongue",
//   // "evil",
//   // "clothing",
// ]);
